// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "b04ed82d-2803-4c58-8dbb-125649a27be1");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1544649634);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1544649754);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1545078871);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1545248227);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1545251437);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1544649514);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1544651422);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1544649874);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{92cfa9d6-6a76-4a5f-b7ba-ca36285f1bf1}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1544166000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1545251412140");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1545253234140");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1545248205348");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1545251805348");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181121180444");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1545251408");
user_pref("browser.startup.homepage_override.buildID", "20181121180444");
user_pref("browser.startup.homepage_override.mstone", "63.0.3");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"webextension_metamask_io-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\",\"webextension_metamask_io-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "63.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "e5ff27db592943a4b650b8180604ead8");
user_pref("extensions.blocklist.lastModified", "Tue, 11 Dec 2018 16:08:04 GMT");
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1544649635);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181121180444");
user_pref("extensions.lastAppVersion", "63.0.3");
user_pref("extensions.lastPlatformVersion", "63.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{10f6d415-e80b-41bd-a52c-a4a7c4338f3f}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"875f9a92-8776-46b1-94d5-70f8329acfb6\",\"webcompat@mozilla.org\":\"7fad7b1e-594d-4154-b2aa-c5c6e378cbd3\",\"screenshots@mozilla.org\":\"751f43ab-a918-4c78-b617-bec87b01b191\",\"fxmonitor@mozilla.org\":\"c7c86947-b350-4c4a-b4bf-c1e40c84fcd2\",\"webextension@metamask.io\":\"9860d905-4029-4ca9-b040-c347f5f3174b\"}");
user_pref("idle.lastDailyNotification", 1544655636);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1544045828);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181121180444");
user_pref("media.gmp-manager.lastCheck", 1544649820);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1544655636);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "bc4ba33f-8e6c-4677-b18c-dde9d2212990");
user_pref("services.blocklist.addons.checked", 1545248461);
user_pref("services.blocklist.gfx.checked", 1545248461);
user_pref("services.blocklist.onecrl.checked", 1545248461);
user_pref("services.blocklist.pinning.checked", 1545248461);
user_pref("services.blocklist.plugins.checked", 1545248461);
user_pref("services.settings.clock_skew_seconds", -258);
user_pref("services.settings.last_update_seconds", 1545248461);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1545248461);
user_pref("services.settings.main.tippytop.last_check", 1545248461);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1544045986);
user_pref("toolkit.startup.last_success", 1545251406);
user_pref("toolkit.telemetry.cachedClientID", "e92c7ae4-4aca-4529-ab47-5346704f0640");
user_pref("toolkit.telemetry.previousBuildID", "20181121180444");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
